# version: '3.9'

# services:
#   django:
#     image: django-docker:0.0.1
#     build: .
#     ports:
#       - "8000:8000"
      
version: '3.10'
services:
  django:
    tty: true
    build: 
      context: .
    ports:
      - '7001:8000'
    volumes:
      - /code/adit
      - .:/code

  tests:
    build: 
      context: .
    volumes:
      - /code/adit
      - .:/code
    command: ["python","manage.py","test"]